### ISSUE TITLE
Icon not showing 

### ISSUE THREAD

**Issue by defisit** [Mariusthvdb/custom-icons#30] opened 2022-06-14 14:03 UTC
Hi,

Thank you very much for all the work that was put into 'custom-icons', I like the icons very much. I do have an issue though ;) 
I am using an icon and have it configured as below. The issue is that the icon disappears once the page is refreshed F5. To get it back, I have to edit the main page again and press Klaar (my installation is in Dutch). Same on mobile app. Do I have to include something in the configuration.yaml (extra_module_url:) as with other icon packages like hass-hue-icons.js? 

![image](https://user-images.githubusercontent.com/61313374/173593865-28840f9b-9ff3-4465-a3e9-3386dfc87aff.png)

Like this:

![image](https://user-images.githubusercontent.com/61313374/173594499-741181e2-a032-4b36-b85e-00c89affd50c.png)

**Comment by Mariusthvdb** [comment] 2022-06-16 08:15
no that shouldn't be necessary...

just to be sure, did you install the .js resource (via HACS or manually), or did you try the experimental Custom Integration?

**Comment by defisit** [comment] 2022-06-16 08:37
Using HACS.

**Comment by Mariusthvdb** [comment] 2022-06-16 11:35
mm, cant make that happen:

<img width="324" alt="Schermafbeelding 2022-06-16 om 13 33 54" src="https://user-images.githubusercontent.com/33354141/174061319-6d85219e-f137-40e8-9a8f-7e629b9bd3ca.png">

remains in view, no matter what. and I just now created 2 quick (empty yet) views

anything in the inspector logs you can see?

**Comment by arallsopp** [comment] 2022-06-16 11:57
If you can open the JavaScript console, you should be able to determine whether the library has loaded when those icons don’t appear. 

I’ve had trouble with icons that appear in the menus of the initial page load in [hass-hue-icons](https://github.com/arallsopp/hass-hue-icons). 

I’d try adding the resource line for your dash and retesting, as it could be a similar thing?

**Comment by defisit** [comment] 2022-06-16 12:46
For the inspector logs, I have to include below in cf.yaml?

--
logger:
  default: info
  logs:
    custom_components.hacs: debug
    aiogithubapi: debug
--

Concerning the brower console:




Icon not visible (pressed F5):

![image](https://user-images.githubusercontent.com/61313374/174071084-b28898c0-c791-4fa3-a397-a2702933525f.png)

Console when icon visible (after a Customize UI and pressing Done)

![image](https://user-images.githubusercontent.com/61313374/174071321-ee3cd72c-ef7e-4abb-9901-607465409b1e.png)

It seems libraries are loaded correctly?

**Comment by Mariusthvdb** [comment] 2022-06-16 14:23
no, inspector logs is the frontend, the yaml debug settings are for backend.
if there's a frontend issue of any sorts, it would show

and yes, seems the resource is loaded correctly.

What I did notice in my empty UI dashboard above, is the creating the first view (the one with the home icon) and simply closed thereafter, no icon showed. It wasnt until I added a second tab (also empty) the first tab showed . Thought is was me being clumsy with the UI, so didnt give it a further thought. Now were trying to find a source for an issue, I better mention it ;-)

so going back, I can now reproduce:

<img width="258" alt="Schermafbeelding 2022-06-16 om 16 18 15" src="https://user-images.githubusercontent.com/33354141/174090600-75b00e61-c70b-4dc6-be63-bee263ad743e.png">

which is really odd, because the icon is there, and showing correctly in editor:

<img width="396" alt="Schermafbeelding 2022-06-16 om 16 17 58" src="https://user-images.githubusercontent.com/33354141/174090737-c414d616-892d-43c3-a2f5-2608952a06ec.png">

I wonder if that could be anything in the path we've omitted. Still, in my test view all are showing as they should without a hiccup. This is however yaml configured, so that might be a cue too, icon far right:

<img width="382" alt="Schermafbeelding 2022-06-16 om 16 20 48" src="https://user-images.githubusercontent.com/33354141/174091136-79ae240c-a9a4-4aa6-bdc1-07f6c8527abc.png">

and selected:

<img width="1131" alt="Schermafbeelding 2022-06-16 om 16 20 57" src="https://user-images.githubusercontent.com/33354141/174091224-004da2b5-c657-4a60-9b93-660ad1096adf.png">

all icons on:

<img width="1111" alt="Schermafbeelding 2022-06-16 om 16 21 08" src="https://user-images.githubusercontent.com/33354141/174091290-e6f24e66-0787-495e-bddf-b9bed64b2162.png">

Andy, can you check/verify if there's a difference between yaml and UI dashboards?

**Comment by arallsopp** [comment] 2022-06-27 16:10
> Do I have to include something in the configuration.yaml (extra_module_url:) as with other icon packages like hass-hue-icons.js?

@defisit, I would try that first. I'm unsure why it needs to be done on some installs, but it does seem to remove issues. I added it to solve an intermittent issue where the first page loaded didn't always get the resource in time, but with the frontend extra_module_url in place, have seen many related issues that pop up on the forums disappear.

**Comment by defisit** [comment] 2022-06-28 20:43
> > Do I have to include something in the configuration.yaml (extra_module_url:) as with other icon packages like hass-hue-icons.js?
> 
> 
> 
> @defisit, I would try that first. I'm unsure why it needs to be done on some installs, but it does seem to remove issues. I added it to solve an intermittent issue where the first page loaded didn't always get the resource in time, but with the frontend extra_module_url in place, have seen many related issues that pop up on the forums disappear.
> 
> 

Did that and it works around the issue, thanks!

**Comment by Mariusthvdb** [comment] 2022-07-22 12:44
great, closing

**Closed by Mariusthvdb** 2022-07-22 12:44 UTC
